import java.util.*;

public class AutoGeneratedArray {

    static Scanner console = new Scanner(System.in);
    static Random random = new Random();

    public static void main(String[] args) {

        int n = inputNumberOfArrays();
        Integer[][] array = new Integer[n][];
        ArrayList<Integer> listOfLengths = new ArrayList<>();

        for (int i = 0; i < n; i++) {
            int randomLength = generateRandomNumber(1000);

            if (i > 0) {
                while (listOfLengths.contains(randomLength)) {
                    randomLength = generateRandomNumber(1000);
                }
            }
            listOfLengths.add(i, randomLength);

            array[i] = new Integer[randomLength];
            for (int j = 0; j < randomLength; j++) {
                array[i][j] = generateRandomNumber(10000);
            }
        }

        for (int i = 0; i < n; i++) {
            if (array[i].length % 2 == 0) {
                Arrays.sort(array[i]);
            } else {
                Arrays.sort(array[i], Collections.reverseOrder());
            }
        }

        for (int i = 0; i < n; i++) {
            System.out.println(Arrays.toString(array[i]));
        }

    }

    static int inputNumberOfArrays() {
        System.out.println("Введите количество массивов (натуральное число от 1 до 1000");
        return console.nextInt();
    }

    static int generateRandomNumber(int bound) {
        return random.nextInt(bound) + 1;
    }

}
